/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-digitalocean-api/apis/spacesbucket/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeObjects implements ObjectInterface
type FakeObjects struct {
	Fake *FakeSpacesbucketV1alpha1
	ns   string
}

var objectsResource = schema.GroupVersionResource{Group: "spacesbucket.digitalocean.kubeform.com", Version: "v1alpha1", Resource: "objects"}

var objectsKind = schema.GroupVersionKind{Group: "spacesbucket.digitalocean.kubeform.com", Version: "v1alpha1", Kind: "Object"}

// Get takes name of the object, and returns the corresponding object object, and an error if there is any.
func (c *FakeObjects) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Object, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(objectsResource, c.ns, name), &v1alpha1.Object{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Object), err
}

// List takes label and field selectors, and returns the list of Objects that match those selectors.
func (c *FakeObjects) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ObjectList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(objectsResource, objectsKind, c.ns, opts), &v1alpha1.ObjectList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ObjectList{ListMeta: obj.(*v1alpha1.ObjectList).ListMeta}
	for _, item := range obj.(*v1alpha1.ObjectList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested objects.
func (c *FakeObjects) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(objectsResource, c.ns, opts))

}

// Create takes the representation of a object and creates it.  Returns the server's representation of the object, and an error, if there is any.
func (c *FakeObjects) Create(ctx context.Context, object *v1alpha1.Object, opts v1.CreateOptions) (result *v1alpha1.Object, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(objectsResource, c.ns, object), &v1alpha1.Object{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Object), err
}

// Update takes the representation of a object and updates it. Returns the server's representation of the object, and an error, if there is any.
func (c *FakeObjects) Update(ctx context.Context, object *v1alpha1.Object, opts v1.UpdateOptions) (result *v1alpha1.Object, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(objectsResource, c.ns, object), &v1alpha1.Object{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Object), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeObjects) UpdateStatus(ctx context.Context, object *v1alpha1.Object, opts v1.UpdateOptions) (*v1alpha1.Object, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(objectsResource, "status", c.ns, object), &v1alpha1.Object{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Object), err
}

// Delete takes name of the object and deletes it. Returns an error if one occurs.
func (c *FakeObjects) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(objectsResource, c.ns, name), &v1alpha1.Object{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeObjects) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(objectsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ObjectList{})
	return err
}

// Patch applies the patch and returns the patched object.
func (c *FakeObjects) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Object, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(objectsResource, c.ns, name, pt, data, subresources...), &v1alpha1.Object{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Object), err
}
