/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package externalversions

import (
	"fmt"

	v1alpha1 "kubeform.dev/provider-digitalocean-api/apis/app/v1alpha1"
	cdnv1alpha1 "kubeform.dev/provider-digitalocean-api/apis/cdn/v1alpha1"
	certificatev1alpha1 "kubeform.dev/provider-digitalocean-api/apis/certificate/v1alpha1"
	containerregistryv1alpha1 "kubeform.dev/provider-digitalocean-api/apis/containerregistry/v1alpha1"
	customv1alpha1 "kubeform.dev/provider-digitalocean-api/apis/custom/v1alpha1"
	databasev1alpha1 "kubeform.dev/provider-digitalocean-api/apis/database/v1alpha1"
	domainv1alpha1 "kubeform.dev/provider-digitalocean-api/apis/domain/v1alpha1"
	dropletv1alpha1 "kubeform.dev/provider-digitalocean-api/apis/droplet/v1alpha1"
	firewallv1alpha1 "kubeform.dev/provider-digitalocean-api/apis/firewall/v1alpha1"
	floatingipv1alpha1 "kubeform.dev/provider-digitalocean-api/apis/floatingip/v1alpha1"
	kubernetesv1alpha1 "kubeform.dev/provider-digitalocean-api/apis/kubernetes/v1alpha1"
	loadbalancerv1alpha1 "kubeform.dev/provider-digitalocean-api/apis/loadbalancer/v1alpha1"
	projectv1alpha1 "kubeform.dev/provider-digitalocean-api/apis/project/v1alpha1"
	recordv1alpha1 "kubeform.dev/provider-digitalocean-api/apis/record/v1alpha1"
	spacesbucketv1alpha1 "kubeform.dev/provider-digitalocean-api/apis/spacesbucket/v1alpha1"
	sshv1alpha1 "kubeform.dev/provider-digitalocean-api/apis/ssh/v1alpha1"
	tagv1alpha1 "kubeform.dev/provider-digitalocean-api/apis/tag/v1alpha1"
	volumev1alpha1 "kubeform.dev/provider-digitalocean-api/apis/volume/v1alpha1"
	vpcv1alpha1 "kubeform.dev/provider-digitalocean-api/apis/vpc/v1alpha1"

	schema "k8s.io/apimachinery/pkg/runtime/schema"
	cache "k8s.io/client-go/tools/cache"
)

// GenericInformer is type of SharedIndexInformer which will locate and delegate to other
// sharedInformers based on type
type GenericInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() cache.GenericLister
}

type genericInformer struct {
	informer cache.SharedIndexInformer
	resource schema.GroupResource
}

// Informer returns the SharedIndexInformer.
func (f *genericInformer) Informer() cache.SharedIndexInformer {
	return f.informer
}

// Lister returns the GenericLister.
func (f *genericInformer) Lister() cache.GenericLister {
	return cache.NewGenericLister(f.Informer().GetIndexer(), f.resource)
}

// ForResource gives generic access to a shared informer of the matching type
// TODO extend this to unknown resources with a client pool
func (f *sharedInformerFactory) ForResource(resource schema.GroupVersionResource) (GenericInformer, error) {
	switch resource {
	// Group=app.digitalocean.kubeform.com, Version=v1alpha1
	case v1alpha1.SchemeGroupVersion.WithResource("apps"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.App().V1alpha1().Apps().Informer()}, nil

		// Group=cdn.digitalocean.kubeform.com, Version=v1alpha1
	case cdnv1alpha1.SchemeGroupVersion.WithResource("cdns"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Cdn().V1alpha1().Cdns().Informer()}, nil

		// Group=certificate.digitalocean.kubeform.com, Version=v1alpha1
	case certificatev1alpha1.SchemeGroupVersion.WithResource("certificates"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Certificate().V1alpha1().Certificates().Informer()}, nil

		// Group=containerregistry.digitalocean.kubeform.com, Version=v1alpha1
	case containerregistryv1alpha1.SchemeGroupVersion.WithResource("containerregistries"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Containerregistry().V1alpha1().ContainerRegistries().Informer()}, nil
	case containerregistryv1alpha1.SchemeGroupVersion.WithResource("dockercredentialses"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Containerregistry().V1alpha1().DockerCredentialses().Informer()}, nil

		// Group=custom.digitalocean.kubeform.com, Version=v1alpha1
	case customv1alpha1.SchemeGroupVersion.WithResource("images"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Custom().V1alpha1().Images().Informer()}, nil

		// Group=database.digitalocean.kubeform.com, Version=v1alpha1
	case databasev1alpha1.SchemeGroupVersion.WithResource("clusters"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Database().V1alpha1().Clusters().Informer()}, nil
	case databasev1alpha1.SchemeGroupVersion.WithResource("connectionpools"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Database().V1alpha1().ConnectionPools().Informer()}, nil
	case databasev1alpha1.SchemeGroupVersion.WithResource("dbs"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Database().V1alpha1().Dbs().Informer()}, nil
	case databasev1alpha1.SchemeGroupVersion.WithResource("firewalls"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Database().V1alpha1().Firewalls().Informer()}, nil
	case databasev1alpha1.SchemeGroupVersion.WithResource("replicas"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Database().V1alpha1().Replicas().Informer()}, nil
	case databasev1alpha1.SchemeGroupVersion.WithResource("users"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Database().V1alpha1().Users().Informer()}, nil

		// Group=domain.digitalocean.kubeform.com, Version=v1alpha1
	case domainv1alpha1.SchemeGroupVersion.WithResource("domains"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Domain().V1alpha1().Domains().Informer()}, nil

		// Group=droplet.digitalocean.kubeform.com, Version=v1alpha1
	case dropletv1alpha1.SchemeGroupVersion.WithResource("droplets"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Droplet().V1alpha1().Droplets().Informer()}, nil
	case dropletv1alpha1.SchemeGroupVersion.WithResource("snapshots"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Droplet().V1alpha1().Snapshots().Informer()}, nil

		// Group=firewall.digitalocean.kubeform.com, Version=v1alpha1
	case firewallv1alpha1.SchemeGroupVersion.WithResource("firewalls"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Firewall().V1alpha1().Firewalls().Informer()}, nil

		// Group=floatingip.digitalocean.kubeform.com, Version=v1alpha1
	case floatingipv1alpha1.SchemeGroupVersion.WithResource("assignments"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Floatingip().V1alpha1().Assignments().Informer()}, nil
	case floatingipv1alpha1.SchemeGroupVersion.WithResource("floatingips"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Floatingip().V1alpha1().FloatingIPs().Informer()}, nil

		// Group=kubernetes.digitalocean.kubeform.com, Version=v1alpha1
	case kubernetesv1alpha1.SchemeGroupVersion.WithResource("clusters"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Kubernetes().V1alpha1().Clusters().Informer()}, nil
	case kubernetesv1alpha1.SchemeGroupVersion.WithResource("nodepools"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Kubernetes().V1alpha1().NodePools().Informer()}, nil

		// Group=loadbalancer.digitalocean.kubeform.com, Version=v1alpha1
	case loadbalancerv1alpha1.SchemeGroupVersion.WithResource("loadbalancers"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Loadbalancer().V1alpha1().Loadbalancers().Informer()}, nil

		// Group=project.digitalocean.kubeform.com, Version=v1alpha1
	case projectv1alpha1.SchemeGroupVersion.WithResource("projects"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Project().V1alpha1().Projects().Informer()}, nil
	case projectv1alpha1.SchemeGroupVersion.WithResource("resourceses"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Project().V1alpha1().Resourceses().Informer()}, nil

		// Group=record.digitalocean.kubeform.com, Version=v1alpha1
	case recordv1alpha1.SchemeGroupVersion.WithResource("records"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Record().V1alpha1().Records().Informer()}, nil

		// Group=spacesbucket.digitalocean.kubeform.com, Version=v1alpha1
	case spacesbucketv1alpha1.SchemeGroupVersion.WithResource("objects"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Spacesbucket().V1alpha1().Objects().Informer()}, nil
	case spacesbucketv1alpha1.SchemeGroupVersion.WithResource("spacesbuckets"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Spacesbucket().V1alpha1().SpacesBuckets().Informer()}, nil

		// Group=ssh.digitalocean.kubeform.com, Version=v1alpha1
	case sshv1alpha1.SchemeGroupVersion.WithResource("keys"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Ssh().V1alpha1().Keys().Informer()}, nil

		// Group=tag.digitalocean.kubeform.com, Version=v1alpha1
	case tagv1alpha1.SchemeGroupVersion.WithResource("tags"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Tag().V1alpha1().Tags().Informer()}, nil

		// Group=volume.digitalocean.kubeform.com, Version=v1alpha1
	case volumev1alpha1.SchemeGroupVersion.WithResource("attachments"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Volume().V1alpha1().Attachments().Informer()}, nil
	case volumev1alpha1.SchemeGroupVersion.WithResource("snapshots"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Volume().V1alpha1().Snapshots().Informer()}, nil
	case volumev1alpha1.SchemeGroupVersion.WithResource("volumes"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Volume().V1alpha1().Volumes().Informer()}, nil

		// Group=vpc.digitalocean.kubeform.com, Version=v1alpha1
	case vpcv1alpha1.SchemeGroupVersion.WithResource("vpcs"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Vpc().V1alpha1().Vpcs().Informer()}, nil

	}

	return nil, fmt.Errorf("no informer found for %v", resource)
}
