/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-digitalocean-api/apis/database/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeConnectionPools implements ConnectionPoolInterface
type FakeConnectionPools struct {
	Fake *FakeDatabaseV1alpha1
	ns   string
}

var connectionpoolsResource = schema.GroupVersionResource{Group: "database.digitalocean.kubeform.com", Version: "v1alpha1", Resource: "connectionpools"}

var connectionpoolsKind = schema.GroupVersionKind{Group: "database.digitalocean.kubeform.com", Version: "v1alpha1", Kind: "ConnectionPool"}

// Get takes name of the connectionPool, and returns the corresponding connectionPool object, and an error if there is any.
func (c *FakeConnectionPools) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ConnectionPool, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(connectionpoolsResource, c.ns, name), &v1alpha1.ConnectionPool{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ConnectionPool), err
}

// List takes label and field selectors, and returns the list of ConnectionPools that match those selectors.
func (c *FakeConnectionPools) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ConnectionPoolList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(connectionpoolsResource, connectionpoolsKind, c.ns, opts), &v1alpha1.ConnectionPoolList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ConnectionPoolList{ListMeta: obj.(*v1alpha1.ConnectionPoolList).ListMeta}
	for _, item := range obj.(*v1alpha1.ConnectionPoolList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested connectionPools.
func (c *FakeConnectionPools) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(connectionpoolsResource, c.ns, opts))

}

// Create takes the representation of a connectionPool and creates it.  Returns the server's representation of the connectionPool, and an error, if there is any.
func (c *FakeConnectionPools) Create(ctx context.Context, connectionPool *v1alpha1.ConnectionPool, opts v1.CreateOptions) (result *v1alpha1.ConnectionPool, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(connectionpoolsResource, c.ns, connectionPool), &v1alpha1.ConnectionPool{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ConnectionPool), err
}

// Update takes the representation of a connectionPool and updates it. Returns the server's representation of the connectionPool, and an error, if there is any.
func (c *FakeConnectionPools) Update(ctx context.Context, connectionPool *v1alpha1.ConnectionPool, opts v1.UpdateOptions) (result *v1alpha1.ConnectionPool, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(connectionpoolsResource, c.ns, connectionPool), &v1alpha1.ConnectionPool{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ConnectionPool), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeConnectionPools) UpdateStatus(ctx context.Context, connectionPool *v1alpha1.ConnectionPool, opts v1.UpdateOptions) (*v1alpha1.ConnectionPool, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(connectionpoolsResource, "status", c.ns, connectionPool), &v1alpha1.ConnectionPool{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ConnectionPool), err
}

// Delete takes name of the connectionPool and deletes it. Returns an error if one occurs.
func (c *FakeConnectionPools) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(connectionpoolsResource, c.ns, name), &v1alpha1.ConnectionPool{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeConnectionPools) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(connectionpoolsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ConnectionPoolList{})
	return err
}

// Patch applies the patch and returns the patched connectionPool.
func (c *FakeConnectionPools) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ConnectionPool, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(connectionpoolsResource, c.ns, name, pt, data, subresources...), &v1alpha1.ConnectionPool{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ConnectionPool), err
}
