/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// ObjectListerExpansion allows custom methods to be added to
// ObjectLister.
type ObjectListerExpansion interface{}

// ObjectNamespaceListerExpansion allows custom methods to be added to
// ObjectNamespaceLister.
type ObjectNamespaceListerExpansion interface{}

// SpacesBucketListerExpansion allows custom methods to be added to
// SpacesBucketLister.
type SpacesBucketListerExpansion interface{}

// SpacesBucketNamespaceListerExpansion allows custom methods to be added to
// SpacesBucketNamespaceLister.
type SpacesBucketNamespaceListerExpansion interface{}
