/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// ClusterListerExpansion allows custom methods to be added to
// ClusterLister.
type ClusterListerExpansion interface{}

// ClusterNamespaceListerExpansion allows custom methods to be added to
// ClusterNamespaceLister.
type ClusterNamespaceListerExpansion interface{}

// ConnectionPoolListerExpansion allows custom methods to be added to
// ConnectionPoolLister.
type ConnectionPoolListerExpansion interface{}

// ConnectionPoolNamespaceListerExpansion allows custom methods to be added to
// ConnectionPoolNamespaceLister.
type ConnectionPoolNamespaceListerExpansion interface{}

// DbListerExpansion allows custom methods to be added to
// DbLister.
type DbListerExpansion interface{}

// DbNamespaceListerExpansion allows custom methods to be added to
// DbNamespaceLister.
type DbNamespaceListerExpansion interface{}

// FirewallListerExpansion allows custom methods to be added to
// FirewallLister.
type FirewallListerExpansion interface{}

// FirewallNamespaceListerExpansion allows custom methods to be added to
// FirewallNamespaceLister.
type FirewallNamespaceListerExpansion interface{}

// ReplicaListerExpansion allows custom methods to be added to
// ReplicaLister.
type ReplicaListerExpansion interface{}

// ReplicaNamespaceListerExpansion allows custom methods to be added to
// ReplicaNamespaceLister.
type ReplicaNamespaceListerExpansion interface{}

// UserListerExpansion allows custom methods to be added to
// UserLister.
type UserListerExpansion interface{}

// UserNamespaceListerExpansion allows custom methods to be added to
// UserNamespaceLister.
type UserNamespaceListerExpansion interface{}
